### ISSUE TITLE
Chocolaty install fails on some VMs

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-baseline-builder#48]
I'm hitting an issue where chocolaty fails to install.  Specifically, in the /tmp/packer-powershell-provisioner* script.
The line  `iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))` fails with error
```
Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure _x000D__x000A
```
Specifically, this fails repeatedly on Windows 10x64 1703, but not on Windows 10x64 1809?  
To make sure there was no networking issue, I added an ipconfig and ping command before the `DownloadString` instruction, and both look good:
```
    vmware-iso: Pinging 8.8.8.8 with 32 bytes of data:
    vmware-iso: Reply from 8.8.8.8: bytes=32 time=26ms TTL=52
    vmware-iso: Reply from 8.8.8.8: bytes=32 time=21ms TTL=52
    vmware-iso: Reply from 8.8.8.8: bytes=32 time=21ms TTL=52
    vmware-iso: Reply from 8.8.8.8: bytes=32 time=18ms TTL=52
    vmware-iso:
    vmware-iso: Ping statistics for 8.8.8.8:
    vmware-iso: Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
    vmware-iso: Approximate round trip times in milli-seconds:
    vmware-iso: Minimum = 18ms, Maximum = 26ms, Average = 21ms
    vmware-iso:
    vmware-iso: Windows IP Configuration
    vmware-iso:
    vmware-iso:
    vmware-iso: Ethernet adapter Ethernet0:
    vmware-iso:
    vmware-iso: Connection-specific DNS Suffix  . : moose
    vmware-iso: IPv6 Address. . . . . . . . . . . : [redacted]
    vmware-iso: IPv6 Address. . . . . . . . . . . : [redacted]
    vmware-iso: Temporary IPv6 Address. . . . . . : [redacted]
    vmware-iso: Link-local IPv6 Address . . . . . : [redacted]
    vmware-iso: IPv4 Address. . . . . . . . . . . : 192.168.134.101
    vmware-iso: Subnet Mask . . . . . . . . . . . : 255.255.255.0
    vmware-iso: Default Gateway . . . . . . . . . : [redacted]
    vmware-iso: 192.168.134.254
    vmware-iso:
    vmware-iso: Tunnel adapter Teredo Tunneling Pseudo-Interface:
    vmware-iso:
    vmware-iso: Connection-specific DNS Suffix  . :
    vmware-iso: IPv6 Address. . . . . . . . . . . : [redacted]
    vmware-iso: Link-local IPv6 Address . . . . . : [redacted]
    vmware-iso: Default Gateway . . . . . . . . . :
    vmware-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure _x000D__x000A_</S><S S="Error">channel."_x000D__x000A_</S><S S="Error">At C:\Windows\Temp\script.ps1:1 char:88_x000D__x000A_</S><S S="Error">+ ... ; ipconfig; iex ((new-object net.webclient).DownloadString('https://c ..._x000D__x000A_</S><S S="Error">+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : WebException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>

```
So it is not a network connection issue.  More curiously, this worked on another machine on Saturday, so I'm kind of at a loss as to why this is popping up.  I could believe an issue with TLS if it were an older OS, but I would think Windows 10 1703 would be OK with crypto libraries for basic support.
